### ISSUE TITLE
boost::variant + move only types + gcc 4.7.2 = regression since boost 1.55?

### ISSUE THREAD

**Issue by Dushistov** [boostorg/variant#47]
I try to compile such code with gcc 4.7.2 (g++ -std=c++11):

```C++
#include <boost/variant.hpp>
#include <vector>
#include <memory>


int main()
{ 
  using VarType = boost::variant<std::unique_ptr<double>, int>;
  std::vector<VarType> v;
  v.emplace_back(5);
}
```

and boost-1.66.0. This code doesn't compile, and give error:
```
/home/user/boost_1_66_0/boost/variant/variant.hpp:467:9: error: use of deleted function ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(const std::unique_ptr<_Tp, _Dp>&) [with _Tp = double; _Dp = std::default_delete<double>; std::unique_ptr<_Tp, _Dp> = std::unique_ptr<double>]’
```
[build.txt](https://github.com/boostorg/variant/files/1786339/build.txt)

I thought may be too old compiler (I have to use this version of gcc),
but with boost-1.55 this example compiled just fine without any problems.

Any hints what is going on?

**Comment by rfgplk** [comment]
It appears as though boost::variant isn't moving the value into the underlying container, merely copying it. For some reason, the library falls back on using the copy constructor instead of the move constructor for std::unique_ptr, which is illegal (due to common pointer-sense) hence why the standard disables copying from lvalues. Due to older library differences, the types very likely cannot be unambiguously converted to the destination variant's types. 
See line 467: ` new(storage_) T(operand);`

As for a fix, you should be able to do a dirty hack by using std::shared_ptr, although I imagine you don't want to do that.

**Comment by Dushistov** [comment]
Thank you, @rfgplk for reply.

> As for a fix, you should be able to do a dirty hack by using std::shared_ptr, although I imagine you don't want to do that.

Yeah, this is the last variant. `std::unique_ptr` was an example of move only class. In real code I use my own move only type, so I have to do two allocations.

> Due to the older library differences, the types very likely cannot be unambiguously converted to the destination variant's types

I start bisecting looks like the problem is in dependicies of `variant`, not in `variant` by it self.

boost-1.60.0 - good
boost-1.61.0 - bad

but if I switch main repo to `boost-1.60.0` and `variant` submodule to `boost-1.66.0` all were compiled fine.

Will try to bisect concrete commit that cause problem.

**Comment by Dushistov** [comment]
@rfgplk 

I found commit that cause problem:

https://github.com/boostorg/type_traits/commit/1f3a3a1553dc316ed002354dce3ba3f081b2e102

After this change from @jzmaddock `gcc 4.7.2`, `boost::variant`  and `std::unique_ptr`  ceased to be friends.

**Comment by rfgplk** [comment]
Looks like you pinpointed the correct commit, nice work. The problem is that the boost source is literally full of workarounds / cheap fixes instead of providing proper solutions to problems. 

If you stated that the code worked properly on `boost-1.60.0`, you could add an additional workaround for your specific compiler version reversing the change.
ie 

`#if BOOST_WORKAROUND(BOOST_GCC_VERSION, != YOUR_VERSION)
...
 #elif BOOST_WORKAROUND(BOOST_GCC_VERSION, < 40700)
...
`
or whatever you need to do.
This way it should maintain full compatibility with the old code and allow you to use your features, but the decision on the boost team to support such `workarounds` is ridiculous since it permits unreadable and nonmaintainable code in the future.

**Comment by Dushistov** [comment]
Just for record (may be google bring somebody here), I solved it in such way:

```diff
--- a/boost/type_traits/is_nothrow_move_constructible.hpp
+++ b/boost/type_traits/is_nothrow_move_constructible.hpp
@@ -27,7 +27,7 @@ struct is_nothrow_move_constructible : public integral_constant<bool, BOOST_IS_N
 template <class T> struct is_nothrow_move_constructible<volatile T> : public ::boost::false_type {};
 template <class T> struct is_nothrow_move_constructible<const volatile T> : public ::boost::false_type{};
 
-#elif !defined(BOOST_NO_CXX11_NOEXCEPT) && !defined(BOOST_NO_SFINAE_EXPR) && !BOOST_WORKAROUND(BOOST_GCC_VERSION, < 40800)
+#elif !defined(BOOST_NO_CXX11_NOEXCEPT) && !defined(BOOST_NO_SFINAE_EXPR) && !BOOST_WORKAROUND(BOOST_GCC_VERSION, < 40700)
 
 #include <boost/type_traits/declval.hpp>
 #include <boost/utility/enable_if.hpp>

```

@rfgplk, I am not sure that my `gcc` is pure vanilla, it is old, debian based distribution,
 have no idea what patches were applied. May be it will works with my gcc 4.7.2 and failed with other gcc 4.7.2

**Comment by jzmaddock** [comment]
OK, what you've done is basically revert the patches for this issue: https://svn.boost.org/trac10/ticket/11904.  The basic issue here is that these traits frequently fail to compile with gcc-4.7.x, which in turn breaks Boost.Optional.  But as you've discovered, the fix breaks variant in this specific situation.

Longer explanation:

* There will always be some older compiler which either don't implement noexcept or rvalue references for which these traits necessarily return false for all types.   The workaround is absolutely required in that situation and hopefully uncontroversial.
* There are a number of compiler releases which do implement noexcept and/or rvalue refs, but they are too buggy to be used in these traits.  Normally this is harmless, albeit you loose some optimisations.  The one exception is a moveable, but non-copyable type as you've discovered.

I'm looking at this again in case I made a mistake (not unheard of, but don't hold your breath).

**Comment by jzmaddock** [comment]
>Looks like you pinpointed the correct commit, nice work. The problem is that the boost source is literally full of workarounds / cheap fixes instead of providing proper solutions to problems.

The compiler frequently generates internal-compiler-errors when you use noexcept, what exactly would be a proper fix?

>but the decision on the boost team to support such workarounds is ridiculous since it permits unreadable and nonmaintainable code in the future.

OK, we could ship just the standard conforming code and remove the workarounds, then all older gcc versions like this would just choke on the header which would hardly help the OP.

**Comment by Dushistov** [comment]
@jzmaddock I use gcc 4.7.2. If you have no this version of gcc,
I can run tests using for your change it if you give hint how to run tests.

**Comment by jzmaddock** [comment]
from the boost root directory, and assuming you have already bootstrapped b2, then:

cd libs/type_traits/test
../../../b2 --toolset=gcc-4.7.2 cxxflags=-std=c++11

But... I've just realised I inadvertently ran my tests in the default C++03 mode, so I need to go back and re-check.

**Comment by jzmaddock** [comment]
Travis CI with 4.7.3 passed OK.
