### ISSUE TITLE
Define std::hash<boost::variant<Ts...>> for compat with std::variant

### ISSUE THREAD

**Issue by alex-weej** [boostorg/variant#49]
As in https://github.com/boostorg/optional/issues/55 for optional, it would be useful to provide this so we can use C++11 unordered_map with boost::variant and have a similar experience to C++17 std::variant.

@akrzemi1

**Comment by apolukhin** [comment]
This is a tempting idea however it has many complications:
* libc++ defines `hash` in namespace `std::__1::` rather than in namespace `std::`
* VC defined `class hash`, rather than `struct hash`.
* ???

@akrzemi1 have you dealt with those issues? Probably we need a common solution here (some macro in Boost.Config to specialize `std::hash`?)

**Comment by akrzemi1** [comment]
No. Did not address it yet in `boost::optional`. However, in this implementation of Optional: https://github.com/akrzemi1/Optional/ I have simply added a specialization of `std::hash` and never heard any complaints about it. Maybe nobody uses it. Or maybe the problems you describe apply only to pre-c++11 compilers?

**Comment by apolukhin** [comment]
Probably all my problems are because of the forward declaration of `std::hash`. I'll try without is soon.

**Comment by apolukhin** [comment]
Looks like 31dcc43 does the job. I'll merge it after the 1.70 release

**Comment by apolukhin** [comment]
Fixed in #65
